-- CreateTable
CREATE TABLE `admin` (
    `adminID` INTEGER NOT NULL AUTO_INCREMENT,
    `adminName` VARCHAR(191) NOT NULL DEFAULT '',
    `email` VARCHAR(191) NOT NULL DEFAULT '',
    `password` VARCHAR(191) NOT NULL DEFAULT '',

    PRIMARY KEY (`adminID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `car` (
    `carID` INTEGER NOT NULL AUTO_INCREMENT,
    `nopol` INTEGER NOT NULL DEFAULT 0,
    `merek_mobil` VARCHAR(191) NOT NULL DEFAULT '',
    `harga_perhari` INTEGER NOT NULL DEFAULT 0,

    PRIMARY KEY (`carID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `rent` (
    `rentID` INTEGER NOT NULL AUTO_INCREMENT,
    `adminID` INTEGER NOT NULL DEFAULT 0,
    `carID` INTEGER NOT NULL DEFAULT 0,
    `nama_penyewa` VARCHAR(191) NOT NULL DEFAULT '',
    `tanggal` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `lama_sewa` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `total_bayar` INTEGER NOT NULL DEFAULT 0,

    PRIMARY KEY (`rentID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `rent` ADD CONSTRAINT `rent_carID_fkey` FOREIGN KEY (`carID`) REFERENCES `car`(`carID`) ON DELETE RESTRICT ON UPDATE CASCADE;
